### ISSUE TITLE
Getting queue length

### ISSUE THREAD

**Issue by dotwaffle** [rounds/go-bqstreamer#15]
At the moment, `rows` is not exported, so I can't access it to run `len()` on. I don't mind implementing it myself, but would you prefer it implemented as an interface, or to export `rows`?

**Comment by oryband** [comment]
related to #9

**Comment by oryband** [comment]
@dotwaffle closed by #21 for `SyncWorker`. For `AsyncWorkerGroup` it is a bit tricky, see #9.
